name: Hello World
on: push
jobs: 
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: Run a single-line script
      run: echo "Hello World"
  my_second_job:
    name: My Second Job
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . -j 2
    - name: runP
      run: echo "Finish !"


